# -*- coding: utf-8 -*-
"""Fraud_Detection model -2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tPMebjty1sUoYmRGy74iQB9McYASFv2d
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.utils import resample

df = pd.read_csv("/content/PS_20174392719_1491204439457_log.csv")

df.head()

df.tail()

df.info()

df.isnull().sum()

# Drop columns
cols_to_drop = ['nameOrig', 'nameDest', 'isFlaggedFraud']
df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])

df = df.fillna(0)

# Extracting features
 # If (Old Balance - Amount) != New Balance, it's a behavioral red flag.
df['errorBalanceOrig'] = df['newbalanceOrig'] + df['amount'] - df['oldbalanceOrg']

# Feature B: Discrepancy in Destination Account
df['errorBalanceDest'] = df['oldbalanceDest'] + df['amount'] - df['newbalanceDest']

# Feature C: Time Conversion
df['hour_of_day'] = df['step'] % 24

# Encoding categorical data
le = LabelEncoder()
df['type'] = le.fit_transform(df['type'])

# Handling imbalance
print("Balancing dataset...")

# Ensure text columns are handled before splitting
# nameOrig and nameDest are unique IDs and cannot be scaled or used directly in XGBoost
cols_to_drop = ['nameOrig', 'nameDest', 'isFlaggedFraud']
df_prepared = df.drop(columns=[c for c in cols_to_drop if c in df.columns])

# Ensure 'type' is numeric (re-applying encoding if necessary for the current slice)
if df_prepared['type'].dtype == 'object':
    le = LabelEncoder()
    df_prepared['type'] = le.fit_transform(df_prepared['type'])

df_normal = df_prepared[df_prepared['isFraud'] == 0]
df_fraud = df_prepared[df_prepared['isFraud'] == 1]

# Downsample the normal cases to balance the dataset
n_normal_samples = len(df_fraud)
df_normal_downsampled = resample(df_normal,
                                 replace=False,
                                 n_samples=n_normal_samples,
                                 random_state=42)

# Concatenate and Shuffle
df_final = pd.concat([df_normal_downsampled, df_fraud])
df_final = df_final.sample(frac=1, random_state=42).reset_index(drop=True)

print(f"Final dataset shape after balancing: {df_final.shape}")

# Define features (X) and target (y)
X = df_final.drop('isFraud', axis=1)
y = df_final['isFraud']

# Scale numerical features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)

print("Data preprocessing and splitting complete. Ready for model training.")

import time
import xgboost as xgb
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report

# Initialize the model since it wasn't defined previously due to errors
model = xgb.XGBClassifier(random_state=42)

# 1. Final Training Execution
start_time = time.time()
print("Training the Secure Wealth Twin Engine...")
model.fit(X_train, y_train)
end_time = time.time()

# 2. Generating Predictions for Analysis
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

# 3. Final Accuracy Metrics
# Fixed: accuracy_report changed to accuracy_score
accuracy = accuracy_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_prob)

print("\n" + "="*40)
print(" FINAL DIGITAL TWIN PERFORMANCE")
print("="*40)
print(f"Training Time: {end_time - start_time:.2f} seconds")
print(f"Perfect Accuracy: {accuracy * 100:.5f}%")
print(f"Fraud Detection (ROC-AUC): {roc_auc * 100:.5f}%")
print("="*40)

# 4. Identifying \"Cyber Crime Bugs\" Caught
print("\n SECURITY BREACH ANALYSIS REPORT:")
report = classification_report(y_test, y_pred, output_dict=True)
fraud_recall = report['1.0']['recall'] if '1.0' in report else report['1']['recall']

print(f"Percentage of Scams Caught: {fraud_recall * 100:.2f}%")
print(f" Percentage of False Alarms: {(1 - report['0.0']['precision'] if '0.0' in report else 1 - report['0']['precision']) * 100:.4f}%")

if fraud_recall > 0.99:
    print("\n RESULT: The Twin has achieved 'Secure Health'. It can now distinguish between a legitimate user and a coerced attacker.")

import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.preprocessing import StandardScaler, LabelEncoder
import time

# 1. DATA LOADING & PRE-PROCESSING
DATA_PATH = "PS_20174392719_1491204439457_log.csv"
df = pd.read_csv(DATA_PATH)

le = LabelEncoder()
le.fit(df['type'])

def get_clean_features(row, encoder, scaler_obj):
    """Processes a single row into a model-ready format"""
    feat_values = [
        row['step'],
        encoder.transform([row['type']])[0],
        row['amount'],
        row['oldbalanceOrg'],
        row['newbalanceOrig'],
        row['oldbalanceDest'],
        row['newbalanceDest'],
        row['newbalanceOrig'] + row['amount'] - row['oldbalanceOrg'], # errorBalanceOrig
        row['oldbalanceDest'] + row['amount'] - row['newbalanceDest'], # errorBalanceDest
        row['step'] % 24 # hour
    ]
    dm = xgb.DMatrix(scaler_obj.transform([feat_values]))
    dm.set_label([row['isFraud']])
    return dm

# 2. INITIALIZATION (Establishing the Scaler)
scaler = StandardScaler()
sample = df.sample(2000)
sample_feats = [[
    r['step'], le.transform([r['type']])[0], r['amount'], r['oldbalanceOrg'],
    r['newbalanceOrig'], r['oldbalanceDest'], r['newbalanceDest'],
    r['newbalanceOrig'] + r['amount'] - r['oldbalanceOrg'],
    r['oldbalanceDest'] + r['amount'] - r['newbalanceDest'], r['step'] % 24
] for _, r in sample.iterrows()]
scaler.fit(sample_feats)

# 3. ADAPTIVE TWIN CORE
class WealthTwin:
    def __init__(self, first_row, scaler, le):
        self.scaler = scaler
        self.le = le
        dm = get_clean_features(first_row, self.le, self.scaler)
        self.model = xgb.train({'objective': 'binary:logistic', 'verbosity': 0}, dm, num_boost_round=1)

    def verify_and_evolve(self, row):
        dm_row = get_clean_features(row, self.le, self.scaler)
        raw_pred = self.model.predict(dm_row)[0]

        if raw_pred > 0.5:
            # UNSAFE TRANSACTION FOUND
            status = "Ὢ8 FRAUD DETECTED - BLOCKING IMMEDIATELY"
            action = "Cool down period activated for 5 minutes."
            return {"Type": row['type'], "Amount": f"RS{row['amount']:,.2f}", "Status": status, "Action": action, "Terminal": False}
        else:
            # SAFE TRANSACTION - Terminating Session as requested for non-fraud processing flow
            status = " SAFE"
            action = "Session Terminated (Normal Protocol)"
            return {"Type": row['type'], "Amount": f"RS{row['amount']:,.2f}", "Status": status, "Action": action, "Terminal": True}

# 4. EXECUTION
twin = WealthTwin(df.iloc[0], scaler, le)

print(f"{'TX TYPE':<12} | {'AMOUNT':<15} | {'SYSTEM DECISION'}")
print("-" * 80)

for i in range(10):
    tx_row = df.sample(1).iloc[0]
    result = twin.verify_and_evolve(tx_row)

    print(f"{result['Type']:<12} | {result['Amount']:<15} | {result['Status']}")
    print(f"Action Taken: {result['Action']}")

    if result['Terminal']:
        print("--- End of Transaction Session ---")
        break
    print("-" * 80)



