# -*- coding: utf-8 -*-
"""Fraud_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rE44GHzQhshyebASjUMg2Iy2BowmroZe
"""

# Basic Libraries
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Sklearn utilities
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Evaluation metrics
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    roc_curve
)

# Handling imbalanced data
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler

# ML models
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

# Boosting models
import lightgbm as lgb
from xgboost import XGBClassifier

# Deep Learning
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.optimizers import Adam

# Model saving
import joblib
import pickle

# Warnings
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

# Load data
df = pd.read_csv('/content/creditcard.csv')

df.head()

df.tail()

df.info()

df.isnull().sum()

print(df['Class'].value_counts())

"""Visualization

"""

# Visualization

# Set style
plt.style.use('seaborn-v0_8')
sns.set_palette("husl")
fig, axes = plt.subplots(2, 3, figsize=(18, 12))

# 1. Class distribution
fraud_pct = (df['Class'].value_counts()[1] / len(df)) * 100
axes[0,0].pie([100-fraud_pct, fraud_pct], labels=['Normal', 'Fraud'], autopct='%1.2f%%',
              colors=['skyblue', 'salmon'], explode=[0.1, 0])
axes[0,0].set_title('Fraud Distribution (0.17%)')

# 2. Time distribution
axes[0,1].hist(df['Time'], bins=50, alpha=0.7, color='green', label='Normal')
axes[0,1].hist(df[df['Class']==1]['Time'], bins=50, alpha=0.7, color='red', label='Fraud')
axes[0,1].set_title('Transaction Time Distribution')
axes[0,1].legend()

# 3. Amount distribution
df['Amount_log'] = np.log(df['Amount'] + 1)
axes[0,2].hist(df['Amount_log'], bins=50, alpha=0.7, color='orange')
axes[0,2].set_title('Log Transaction Amount')

# 4. Top fraud-correlated features (V14, V17, V12, V10, V16)
corr_fraud = df.corr()['Class'].abs().sort_values(ascending=False)[1:6]
top_features = corr_fraud.index
for i, feat in enumerate(top_features[:3]):
    axes[1,i].scatter(df[df['Class']==0][feat], df[df['Class']==0]['Amount'],
                     alpha=0.3, s=1, label='Normal')
    axes[1,i].scatter(df[df['Class']==1][feat], df[df['Class']==1]['Amount'],
                     alpha=0.8, s=20, color='red', label='Fraud')
    axes[1,i].set_title(f'{feat} vs Amount')

plt.tight_layout()
plt.show()

# 5. Correlation heatmap (top 15 features)
plt.figure(figsize=(12, 8))
top_corr = df.corr().abs().nlargest(15, 'Class')['Class'].index
sns.heatmap(df[top_corr].corr(), annot=False, cmap='coolwarm', center=0)
plt.title('Top 15 Feature Correlations')
plt.show()

#  FIXED CREDIT CARD FRAUD VISUALIZATION
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
from sklearn.feature_selection import mutual_info_classif

# Professional styling
plt.style.use('default')
colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']
sns.set_palette(colors)

# Create 4x4 dashboard
fig, axes = plt.subplots(4, 4, figsize=(24, 20))
fig.suptitle(' CREDIT CARD FRAUD DETECTION - KEY INSIGHTS', fontsize=24, fontweight='bold')

# 1. CLASS IMBALANCE - Dual visualization
ax = axes[0,0]
counts = df['Class'].value_counts()
ax.pie(counts, labels=[f'Legit\n{counts[0]:,}', f'FRAUD\n{counts[1]}'],
       autopct='%1.1f%%', colors=['#1f77b4', '#d62728'],
       explode=[0, 0.15], startangle=90, shadow=True)
ax.set_title('Dataset Imbalance\n0.17% Fraud Cases', fontweight='bold', pad=20)

axes[0,1].bar(['Legit', 'Fraud'], counts.values, color=['#1f77b4', '#d62728'], alpha=0.8)
axes[0,1].set_title('Transaction Counts', fontweight='bold')
for i, v in enumerate(counts.values):
    axes[0,1].text(i, v+1000, f'{v:,}', ha='center', fontweight='bold')

# 2. TIME PATTERNS - Hourly fraud rate
df['hour'] = (df['Time'] // 3600) % 24
hourly_fraud = df.groupby('hour')['Class'].mean()
axes[0,2].bar(hourly_fraud.index, hourly_fraud.values, color='#d62728', alpha=0.7, width=0.8)
axes[0,2].axhline(y=df['Class'].mean(), color='gray', ls='--', label='Overall Fraud Rate')
axes[0,2].set_title('Fraud Rate by Hour\nNight Spike Detected')
axes[0,2].set_xlabel('Hour of Day')
axes[0,2].set_ylabel('Fraud Probability')
axes[0,2].legend()

# 3. TRANSACTION AMOUNT - Boxplot comparison
df['log_amount'] = np.log1p(df['Amount'])
bp = axes[0,3].boxplot([df[df['Class']==0]['log_amount'], df[df['Class']==1]['log_amount']],
                       labels=['Legit', 'Fraud'], patch_artist=True)
bp['boxes'][0].set_facecolor('#1f77b4')
bp['boxes'][1].set_facecolor('#d62728')
axes[0,3].set_title('Transaction Amounts\nFraud = Higher Values', fontweight='bold')

# 4-8. TOP FRAUD CORRELATION FEATURES
feature_corrs = df.corr()['Class'].abs().sort_values(ascending=False)[1:6]
top_features = feature_corrs.index

for idx, feature in enumerate(top_features):
    row, col = 1 + (idx // 3), (idx % 3)
    ax = axes[row, col]

    legit = df[df['Class'] == 0]
    fraud = df[df['Class'] == 1]

    ax.scatter(legit[feature], legit['Amount'], alpha=0.4, s=8, color='#1f77b4', label='Legit')
    ax.scatter(fraud[feature], fraud['Amount'], alpha=0.9, s=60, color='#d62728',
               edgecolors='black', linewidth=0.8, label='FRAUD')

    corr_val = df[feature].corr(df['Class'])
    ax.set_title(f'{feature}\nCorr: {corr_val:+.3f}', fontweight='bold')
    if idx == 0:
        ax.legend(loc='upper right', fontsize=9)

# 9. V14 DISTRIBUTION - Strongest fraud signal
ax = axes[2,3]
sns.kdeplot(data=df, x='V14', hue='Class', fill=True, alpha=0.6, ax=ax,
            palette=['#1f77b4', '#d62728'])
ax.set_title('V14: Complete Fraud Separation', fontweight='bold')

# 10. CORRELATION MATRIX
top_corr_features = df.corr().abs().nlargest(12, 'Class')['Class'].index
ax = axes[3,0]
sns.heatmap(df[top_corr_features].corr(), annot=False, cmap='RdBu_r', center=0, ax=ax)
ax.set_title('Feature Correlation Matrix', fontweight='bold')

# 11. FIXED FRAUD STATS - BAR CHART INSTEAD OF TABLE
ax = axes[3,1]
metrics = ['Avg Amount', 'Max Amount', 'Peak Hour']
fraud_vals = [df[df['Class']==1]['Amount'].mean(),
              df[df['Class']==1]['Amount'].max(),
              df[df['Class']==1]['hour'].mode()[0]]
legit_vals = [df[df['Class']==0]['Amount'].mean(),
              df[df['Class']==0]['Amount'].max(),
              df[df['Class']==0]['hour'].mode()[0]]

x = np.arange(len(metrics))
width = 0.35
ax.bar(x - width/2, fraud_vals, width, label='Fraud', color='#d62728', alpha=0.8)
ax.bar(x + width/2, legit_vals, width, label='Legit', color='#1f77b4', alpha=0.8)
ax.set_title('Fraud vs Legit Comparison', fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(metrics)
ax.legend()
ax.tick_params(axis='x', rotation=45)

# 12. FRAUD INSIGHTS SUMMARY
ax = axes[3,2]
ax.axis('off')
summary_text = f""" KEY FRAUD INSIGHTS:
• Total: {len(df):,} transactions
• Fraud: {df['Class'].sum():,} cases (0.17%)
• Night fraud: {df[df['hour']>=18]['Class'].mean():.2%}
• Top feature: {top_features[0]}
• Fraud avg: ${df[df['Class']==1]['Amount'].mean():.0f}"""
ax.text(0.05, 0.95, summary_text, transform=ax.transAxes, fontsize=12,
        fontweight='bold', va='top', bbox=dict(boxstyle="round,pad=0.5",
        facecolor='lightyellow', alpha=0.8))

# 13. Unused subplot - fill with feature importance preview
ax = axes[3,3]
mi_scores = mutual_info_classif(df.drop('Class', axis=1), df['Class'], random_state=42)
mi_df = pd.Series(mi_scores, index=df.drop('Class', axis=1).columns).nlargest(10)
mi_df.plot(kind='barh', ax=ax, color='#ff7f0e')
ax.set_title('Top 10 Feature Importance\n(Mutual Information)', fontweight='bold')
ax.tick_params(axis='x', rotation=0)

plt.tight_layout()
plt.subplots_adjust(top=0.92)
plt.show()

# Print insights
print("FRAUD PATTERNS DETECTED:")
print(f"• Peak fraud hours: {sorted(df[df['Class']==1]['hour'].mode().tolist())}")
print(f"• Strongest predictor: {top_features[0]} (corr={feature_corrs.iloc[0]:.3f})")
print(f"• Fraud avg amount: ${df[df['Class']==1]['Amount'].mean():.0f}")
print(f"• Legit avg amount: ${df[df['Class']==0]['Amount'].mean():.0f}")

# Training the model

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print("Train fraud rate:", y_train.mean())
print("Test fraud rate:", y_test.mean())

# ===== 5. SCALE IMPORTANT FEATURES =====

scaler = RobustScaler()

X_train[['Time','Amount']] = scaler.fit_transform(
    X_train[['Time','Amount']]
)

X_test[['Time','Amount']] = scaler.transform(
    X_test[['Time','Amount']]
)

# ===== 6. RANDOM FOREST MODEL =====

rf_model = RandomForestClassifier(

    n_estimators=120,        # fewer trees → faster
    max_depth=10,            # prevents overfitting
    min_samples_split=5,
    min_samples_leaf=2,
    class_weight="balanced", # handles fraud imbalance
    n_jobs=-1,               # use all CPU cores
    random_state=42

)

print("\nTraining Random Forest...")

rf_model.fit(X_train, y_train)


# ===== 7. MODEL PREDICTION =====

y_pred = rf_model.predict(X_test)

y_prob = rf_model.predict_proba(X_test)[:,1]

# ===== 7. MODEL PREDICTION =====

y_pred = rf_model.predict(X_test)

y_prob = rf_model.predict_proba(X_test)[:,1]


# ===== 8. MODEL EVALUATION =====

print("\nConfusion Matrix")

print(confusion_matrix(y_test, y_pred))


print("\nClassification Report")

print(classification_report(y_test, y_pred))


print("ROC-AUC Score:", roc_auc_score(y_test, y_prob))


# ===== 9. SAVE MODEL =====

joblib.dump(rf_model, "fraud_random_forest.pkl")

joblib.dump(scaler, "fraud_scaler.pkl")

print("\nModel Saved Successfully")


# ===== 10. REAL-TIME FRAUD DETECTION FUNCTION =====

def detect_fraud(transaction_df):

    transaction_df = transaction_df.copy()

    transaction_df[['Time','Amount']] = scaler.transform(
        transaction_df[['Time','Amount']]
    )

    probability = rf_model.predict_proba(transaction_df)[:,1][0]

    fraud = probability > 0.35

    return {

        "fraud_detected": bool(fraud),
        "fraud_probability": float(probability)

    }


# ===== 11. TEST MODEL =====

sample = X_test.iloc[[0]]

result = detect_fraud(sample)

print("\nSample Prediction:")

print(result)

class_weight="balanced"

